# .github/workflows/ci.yml
name: ci

on: [push, pull_request]

jobs:
  ci:
    uses: catalyst/catalyst-moodle-workflows/.github/workflows/ci.yml@main
    #secrets:
      # Required if you plan to publish (uncomment the below)
      # moodle_org_token: ${{ secrets.MOODLE_ORG_TOKEN }}
    with:
      codechecker_max_warnings: 0 # CI should now fail on phpcs / code checker warnings.
      disable_behat: true
      disable_grunt: true
      disable_mustache: true # Email templates often require old school html.
      disable_phpunit: true # Very simply so no unit tests needed.
